// 📌 packageData.js

/* Wedding Packages Images */
import GoaBeachWeddingImg from "../assets/Goa Beach Wedding.webp";
import KeralaWeddingImg from "../assets/Kerala Backwater Wedding.webp";
import ShimlaHillWeddingImg from "../assets/Shimla Hill Wedding.jpg";
import UdaipurPalaceWeddingImg from "../assets/Udaipur Palace Wedding.jpg";
import RajasthanDesertWeddingImg from "../assets/Rajasthan Desert Wedding.webp";
import AndamanBeachWeddingImg from "../assets/Andaman Beach Wedding.jpg";
import BaliLuxuryResortImg from "../assets/Luxury Resort Wedding in Bali.jpg";
import JaipurCulturalWeddingImg from "../assets/Cultural Wedding in Jaipur.webp";

/* Couples Packages */
import MaldivesEscapeImg from "../assets/Romantic Maldives Escape.jpg";
import ParisCityOfLoveImg from "../assets/Paris City of Love.webp";
import VeniceGondolaImg from "../assets/Venice Gondola Retreat.webp";
import BaliAdventureRomanceImg from "../assets/Bali Adventure & Romance.webp";
import SantoriniSunsetImg from "../assets/Santorini Sunset Escape.jpg";
import SwissAlpsRetreatImg from "../assets/Swiss Alps Couples Retreat.webp";
import ThailandRomanticImg from "../assets/Thailand Romantic Adventure.avif";
import DubaiLuxuryEscapeImg from "../assets/Dubai Luxury Escape.jpg";

/* Honeymoon Packages */
import MauritiusHoneymoonImg from "../assets/Exotic Mauritius Honeymoon.jpg";
import MaldivesPrivateIslandImg from "../assets/Maldives Private Island Honeymoon.webp";
import HawaiiRomanticGetawayImg from "../assets/Hawaii Romantic Getaway.jpg";
import ThailandIslandHoneymoonImg from "../assets/Thailand Island Honeymoon.jpg";
import SwissRomanticHoneymoonImg from "../assets/Swiss Romantic Honeymoon.avif";
import BaliLuxuryHoneymoonImg from "../assets/Bali Luxury Honeymoon.jpg";
import ItalyHoneymoonImg from "../assets/Italy Honeymoon Package.avif";
import JapanHoneymoonImg from "../assets/Japan Honeymoon Experience.jpg";

/* Solo Packages */
import GoaSoloAdventureImg from "../assets/Goa Solo Adventure.webp";
import RajasthanSoloHeritageImg from "../assets/Rajasthan Solo Heritage Tour.jpg";
import KeralaSoloExplorerImg from "../assets/Kerala Solo Explorer.jpg";
import ThailandSoloBackpackerImg from "../assets/Thailand Solo Backpacker Tour.jpg";
import EuropeSoloExplorerImg from "../assets/Europe Solo Explorer.webp";
import HimachalSoloTrekkingImg from "../assets/Himachal Solo Trekking.webp";

/* Family Packages */
import GoaFamilyFunTripImg from "../assets/Goa Family Fun Trip.webp";
import RajasthanFamilyHeritageImg from "../assets/Rajasthan Family Heritage Tour.jpg";
import KeralaFamilyAdventureImg from "../assets/Kerala Family Adventure.webp";
import HimachalFamilyTripImg from "../assets/Himachal Family Trip.png";

/* Student Packages */
import RajasthanEducationalTripImg from "../assets/Educational Trip to Rajasthan.jpg";
import GoaBeachStudentTripImg from "../assets/Goa Beach Student Trip.jpg";
import HimachalAdventureTripImg from "../assets/Himachal Adventure Trip.png";
import KeralaEducationalTourImg from "../assets/Kerala Educational & Adventure Tour.jpg";
import KolkataDelhiHistoryTourImg from "../assets/Kolkata & Delhi History Tour.jpg";

/* ------------------- ALL PACKAGES ---------------------- */

export const packagesData = [
  /* Wedding Packages */
  { id: 1, name: "Goa Beach Wedding", img: GoaBeachWeddingImg, days: "3 Days", place: "Goa", price: "₹55,000", desc: "A Goa beach wedding is a symphony of coastal romance, where the Arabian Sea serves as the most spectacular, living backdrop for a couple’s vows. The setting sun initiates the magic, casting a golden-hour glow that drenches the entire scene in hues of apricot, rose, and deep saffron. The air, thick with the scent of salt and tropical frangipani, carries the soft, rhythmic sound of gentle waves washing ashore, perfectly harmonizing with the live acoustic music that drifts across the sand.The ceremonial area, often framed by bamboo and sheer fabrics, feels instantly ethereal. The wedding aisle, perhaps marked by delicate shells or cascading white petals, leads to a floral mandap or a simple wooden arch draped with lush, exotic blooms like orchids and lilies. Lanterns and fairy lights are strategically placed, promising a dazzling transition from the warm daylight ceremony to the cool, starlit evening reception. Everything is designed to be effortlessly chic, merging Goan vibrancy with elegant simplicity.", category: "Wedding Packages" },
  { id: 2, name: "Kerala Backwater Wedding", img: KeralaWeddingImg, days: "2 Days", place: "Kerala", price: "₹75,000", desc: "Imagine an exquisite wedding where nature is the grand decorator. A Kerala backwater wedding is an intimate and enchanting affair set against the timeless, tranquil beauty of Kerala, The scenery is an unparalleled canvas of shimmering canals, vast emerald lakes, and a shoreline fringed by countless swaying coconut palms.The primary stage is often a luxurious traditional houseboat (Kettuvallam), beautifully adorned with fresh local flowers like jasmine, marigolds, and white lilies. The boat gently glides through the waters of Alleppey or Kumarakom, creating a uniquely romantic, moving venue. Alternatively, the ceremony might unfold on the lush lake-facing lawns of a heritage resort.", category: "Wedding Packages" },
  { id: 3, name: "Shimla Hill Wedding", img: ShimlaHillWeddingImg, days: "3 Days", place: "Shimla", price: "₹90,000", desc: "A Shimla Hill Wedding is a dream realized high up in the mountains, offering a unique blend of Victorian elegance and majestic Himalayan grandeur. This destination transforms the wedding into a fairytale set amidst the snow-capped peaks and thick, fragrant deodar forests of Himachal Pradesh.The venue is often a historic, charming colonial-era hotel or a luxury resort nestled on a hillside, overlooking the stunning, layered valleys. Imagine the ceremony taking place on an open-air terrace where the clouds drift below you, making you feel literally on top of the world.The crisp, clean mountain air and the panoramic views provide a dramatically beautiful and ever-changing backdrop. The natural light filtering through the pines creates a soft, golden glow that is perfect for photography, giving every moment a timeless, vintage quality. ", category: "Wedding Packages" },
  { id: 4, name: "Udaipur Palace Wedding", img: UdaipurPalaceWeddingImg, days: "2 Days", place: "Udaipur", price: "₹1,20,000", desc: "An Udaipur Palace Wedding is the ultimate dream of fairytale romance and majestic luxury. Set in the magnificent City of Lakes, this event transforms the couple into temporary royalty, surrounded by the historical grandeur of Rajasthan’s heritage.The primary backdrop is a spectacular palace, often situated directly on the shores of Lake Pichola. Venues like the Taj Lake Palace or the Jagmandir Island Palace offer a celestial, floating stage for the most important ceremony, accessible only by elegantly decorated boats.The setting is characterized by intricate Mughal and Rajasthani architecture—ornate domes, carved marble courtyards, sprawling terraces, and detailed jharokhas (balconies). Every corner exudes history, romance, and an unparalleled sense of majesty.The events are choreographed with opulence and vibrant tradition. The Sangeet and Mehendi ceremonies are typically lavish affairs held in grand courtyards or gardens, filled with the sounds of folk music and the sight of brilliant, traditional attire.For the main event, the groom's entry, or Baraat, is a spectacle of its own, often involving decorated elephants, horses, and a procession accompanied by traditional drummers and fireworks, creating a vibrant spectacle against the ancient stone.", category: "Wedding Packages" },
  { id: 5, name: "Rajasthan Desert Wedding", img: RajasthanDesertWeddingImg, days: "2 Days", place: "Jaisalmer", price: "₹95,000", desc: "A Rajasthan Desert Wedding is an exotic and breathtaking experience, marrying the austere beauty of the Thar Desert with the opulent traditions of the Rajput era. It is a celebration defined by its vast, silent, and golden backdrop.The setting is uniquely dramatic: perhaps a magnificent dune camp outside Jaisalmer, a heritage property in the desert sands, or a fortress overlooking the arid landscape. The venue is transformed into a luxurious oasis under the endless sky.The ambiance is one of ancient romance and vibrant colour. The raw, muted tones of the desert sand are brilliantly contrasted by the dazzling, kaleidoscopic textiles and decorations typical of Rajasthan.", category: "Wedding Packages" },
  { id: 6, name: "Andaman Beach Wedding", img: AndamanBeachWeddingImg, days: "3 Days", place: "Andaman", price: "₹1,30,000", desc: "An Andaman Beach Wedding is the ultimate realization of a tropical paradise fantasy. Set on the shores of exotic islands like Havelock (Swaraj Dweep) or Neil (Shaheed Dweep), this celebration is defined by its untouched natural beauty and tranquil, crystal-clear waters.The primary stage is a stretch of powdery white sand, backed by dense, vibrant green foliage and framed by the endless blue horizon. The atmosphere is one of blissful calm, far removed from the noise of the mainland.The ceremony is typically held during the late afternoon, timed perfectly to capture the magnificent sunset over the Bay of Bengal. The soundscape features the gentle lapping of waves and the soft rustle of palms—a natural orchestra for the vows.The decor embraces a bohemian and minimalist tropical aesthetic: bamboo arches, flowing white linen, draped flowers like orchids and hibiscus, and natural elements like sea shells and drift wood. The focus is to complement, not overshadow, the stunning view.", category: "Wedding Packages" },
  { id: 7, name: "Luxury Resort Wedding in Bali", img: BaliLuxuryResortImg, days: "4 Days", place: "Bali", price: "₹1,80,000", desc: "A Luxury Resort Wedding in Bali is a fusion of world-class sophistication and spiritual island tranquility. It is the pinnacle of destination celebrations, set against the backdrop of lush rice paddies, dramatic ocean cliffs, or serene tropical jungles.The venue is typically a five-star international resort, often perched high on the limestone cliffs of Uluwatu or nestled into the terraced hills of Ubud. These resorts boast stunning, architectural chapels, infinity pool decks, or private villas that offer truly mesmerizing views.The ambiance is defined by unparalleled elegance and seamless service. Every detail, from the personalized welcome for guests to the custom culinary experience, is managed with impeccable Balinese hospitality.", category: "Wedding Packages" },
  { id: 8, name: "Cultural Wedding in Jaipur", img: JaipurCulturalWeddingImg, days: "2 Days", place: "Jaipur", price: "₹85,000", desc: "A Cultural Wedding in Jaipur is a magnificent celebration steeped in the vibrant history and artistic traditions of Rajasthan. It is a sensory feast, held amidst the stunning architecture of the pink city where every ceremony is a tribute to heritage.The venue is often a historic City Palace hotel, a grand haveli (mansion), or a luxurious fort property, like the Fairmont or the magnificent Amer Fort-facing resorts. These settings provide an authentic backdrop of Rajput splendour.The events are characterized by dazzling colours and rich traditional customs. The wedding isn't a single day, but a series of vibrant ceremonies—Sangeet, Mehendi, and Haldi—each executed with local flair and intense energy.", category: "Wedding Packages" },

  /* Couples Packages */
  { id: 9, name: "Romantic Maldives Escape", img: MaldivesEscapeImg, days: "3 Days", place: "Maldives", price: "₹1,40,000", desc: "A Romantic Maldives Escape is the global benchmark for secluded luxury and intimate tranquility. This destination is a constellation of tiny, pristine islands, offering couples a sanctuary where the world melts away.The setting is pure, vivid paradise: snow-white silica sands, mesmerizing lagoons in shades of turquoise and sapphire, and the iconic overwater bungalows, seemingly floating on the ocean surface.Accommodation is the cornerstone of the experience. Guests reside in lavish overwater villas with private decks, direct ocean access, and often a personal infinity pool, guaranteeing complete privacy and uninterrupted views.The ambiance is defined by barefoot elegance and profound peace. The only sounds are the gentle lapping of the waves beneath your villa and the occasional call of a seabird.", category: "Couples Packages" },
  { id: 10, name: "Paris City of Love", img: ParisCityOfLoveImg, days: "5 Days", place: "Paris", price: "₹2,20,000", desc: "The city’s reputation for romance is deeply rooted in its stunning Haussmann architecture, its artistic heritage, and its celebration of aesthetic beauty. The very sight of the Eiffel Tower, especially when it begins to sparkle hourly after dark, is an immediate, universally recognized symbol of love and a favourite spot for countless proposals.The River Seine gracefully curves through the city's heart, its banks designated a UNESCO World Heritage site, providing a captivating backdrop. Taking a sunset river cruise, passing iconic landmarks like the Louvre and Notre Dame, feels like drifting through a live-action romance movie.Intimacy is found in the charming cobblestone lanes of Montmartre, the artists' quarter. Here, high atop a hill, the Sacré-Cœur Basilica offers breathtaking panoramic views, while the nearby Mur des Je t'aime (Wall of Love) proclaims I love you in hundreds of languages.", category: "Couples Packages" },
  { id: 11, name: "Venice Gondola Retreat", img: VeniceGondolaImg, days: "4 Days", place: "Venice", price: "₹1,60,000", desc: "A Venice Gondola Retreat offers an unparalleled romantic experience, defined by the city's unique liquid streets and timeless, floating charm. Here is a description, crafted to be around 30 lines, capturing the enchanting essence of this Italian escape.A Venice Gondola Retreat is the quintessential European romantic escape, centered on the city's unique charm where canals replace streets and every turn holds centuries of history and romance.The defining image is the Gondola ride, a serene journey gliding through the labyrinthine waterways. Steered by the traditionally dressed gondolier, whose melodic singing echoes off the ancient walls, this journey is the heartbeat of a Venetian escape.", category: "Couples Packages" },
  { id: 12, name: "Bali Adventure & Romance", img: BaliAdventureRomanceImg, days: "4 Days", place: "Bali", price: "₹1,10,000", desc: "A Bali Adventure & Romance retreat is designed for couples who seek the perfect balance between exhilarating exploration and tranquil, luxurious intimacy. It is a dynamic journey across the Island of the Gods, blending culture, adrenaline, and deep connection.The adventure begins inland, amidst the lush, terraced rice paddies and volcanic landscapes of Ubud. Days are dedicated to exploration: perhaps an early morning hike up Mount Batur to witness a breathtaking sunrise, or white-water rafting down the Ayung River.The romance element is seamlessly integrated into this setting. You might stay in a secluded jungle villa with a private infinity pool overlooking the ravine, enjoying the profound peace and vibrant green canopy.", category: "Couples Packages" },
  { id: 13, name: "Santorini Sunset Escape", img: SantoriniSunsetImg, days: "4 Days", place: "Santorini", price: "₹1,90,000", desc: "A Santorini Sunset Escape is the realization of a postcard dream—a volcanic island paradise famous for its dramatic beauty and its title as the world's premier sunset viewing destination.The setting is instantly recognizable: the iconic whitewashed villages of Oia and Fira, perched precariously atop towering caldera cliffs, contrasted brilliantly by the deep azure of the Aegean Sea.Accommodation is often in a bespoke cave house (yposkafo) or a luxury cliffside villa. These rooms are characterized by their unique, Cycladic architecture and private balconies or plunge pools that offer uninterrupted, sweeping views of the sea and volcano.The ambiance is one of exclusive tranquility and artistic inspiration. The winding, marble-paved pathways invite leisurely exploration, leading to hidden viewpoints, art galleries, and chic boutiques.", category: "Couples Packages" },
  { id: 14, name: "Swiss Alps Couples Retreat", img: SwissAlpsRetreatImg, days: "5 Days", place: "Switzerland", price: "₹2,40,000", desc: "A Swiss Alps Couples Retreat is the ultimate journey into majestic natural beauty and serene alpine luxury. It's an escape where the scale of the mountains humbles and inspires, creating a perfect backdrop for reconnection.The setting is one of breathtaking, pristine wilderness: colossal snow-capped peaks, verdant valleys dotted with traditional chalets, and deep, shimmering turquoise lakes fed by glacial meltwater.Accommodation is typically a charming, luxurious wooden chalet or a five-star hotel in villages like Zermatt or St. Moritz. These retreats offer cozy fireplaces, panoramic windows, and private balconies with direct views of iconic mountains like the Matterhorn.The ambiance is defined by crisp, clean air and peaceful solitude. The soundscape is the soft crunch of snow underfoot in winter, or the distant clanging of cowbells in the summer meadows..", category: "Couples Packages" },
  { id: 15, name: "Thailand Romantic Adventure", img: ThailandRomanticImg, days: "4 Days", place: "Thailand", price: "₹95,000", desc: "A Swiss Alps Couples Retreat is the ultimate journey into majestic natural beauty and serene alpine luxury. It's an escape where the scale of the mountains humbles and inspires, creating a perfect backdrop for reconnection.The setting is one of breathtaking, pristine wilderness: colossal snow-capped peaks, verdant valleys dotted with traditional chalets, and deep, shimmering turquoise lakes fed by glacial meltwater.Accommodation is typically a charming, luxurious wooden chalet or a five-star hotel in villages like Zermatt or St. Moritz. These retreats offer cozy fireplaces, panoramic windows, and private balconies with direct views of iconic mountains like the Matterhorn.The ambiance is defined by crisp, clean air and peaceful solitude. The soundscape is the soft crunch of snow underfoot in winter, or the distant clanging of cowbells in the summer meadows.The escape often begins in the northern hills of Chiang Mai, offering the first taste of adventure. Couples can bond over thrilling experiences like ziplining through the jungle canopy or ethically feeding and bathing elephants at a responsible sanctuary.The romance is amplified by the change in scenery. Imagine sharing a quiet moment during a sunrise hot air balloon ride over the misty rice fields, feeling like the world belongs only to you two.", category: "Couples Packages" },
  { id: 16, name: "Dubai Luxury Escape", img: DubaiLuxuryEscapeImg, days: "3 Days", place: "Dubai", price: "₹1,50,000", desc: "A Dubai Luxury Escape is the definition of modern opulence and audacious ambition. It is a vacation where every experience is elevated, set within a city that constantly redefines the limits of luxury and architectural innovation.The defining feature is the extraordinary skyline, dominated by the towering Burj Khalifa. The retreat includes exclusive access to observation decks and fine-dining restaurants that offer breathtaking, panoramic views of the entire city.Accommodation is in one of the city's iconic seven-star hotels—perhaps on the Palm Jumeirah, in a lavish suite with floor-to-ceiling windows, or a private resort villa with direct beach access to the Arabian Gulf.The days are dedicated to world-class leisure and high-end shopping. Guests explore sprawling malls like the Dubai Mall, indulging in designer goods and viewing spectacles like the captivating Dubai Fountain show.", category: "Couples Packages" },

  /* Honeymoon Packages */
  { id: 17, name: "Exotic Mauritius Honeymoon", img: MauritiusHoneymoonImg, days: "5 Days", place: "Mauritius", price: "₹1,90,000", desc: "An Exotic Mauritius Honeymoon is a dive into a vibrant, volcanic island paradise in the heart of the Indian Ocean, offering a rich tapestry of culture, luxury, and breathtaking natural beauty.The landscape is uniquely captivating, featuring dramatic mountain peaks, lush sugarcane fields, and, most famously, ringed by brilliant white-sand beaches and an extensive, protective coral reef.Accommodation is typically in an exclusive, all-inclusive five-star resort, perhaps a private beach villa or a suite with a private plunge pool overlooking the turquoise lagoon, ensuring total privacy and indulgence.The atmosphere is one of laid-back elegance and genuine warmth, thanks to the island's unique blend of Indian, African, French, and Creole cultures, reflected in the cuisine and the gracious service.", category: "Honeymoon Packages" },
  { id: 18, name: "Maldives Private Island Honeymoon", img: MaldivesPrivateIslandImg, days: "4 Days", place: "Maldives", price: "₹2,10,000", desc: "A Maldives Private Island Honeymoon is the embodiment of exclusive, customized luxury, a journey to a sanctuary where an entire island resort is dedicated to providing profound intimacy and personalized service.", category: "Honeymoon Packages" },
  { id: 19, name: "Hawaii Romantic Getaway", img: HawaiiRomanticGetawayImg, days: "5 Days", place: "Hawaii", price: "₹2,40,000", desc: "A Hawaii Romantic Getaway is an electrifying journey into the heart of the Pacific, offering a perfect blend of dramatic volcanic scenery and laid-back island romance. It is an escape rich in unique Polynesian culture and stunning natural beauty.The landscape is incredibly diverse, ranging from the fiery, active volcanoes of the Big Island to the lush, dramatic sea cliffs of Kauai's Nā Pali Coast and the world-famous surfing beaches of Oahu.Accommodation is often found in an oceanfront resort on Maui or Kauai, featuring spacious lanai (balconies) that offer spectacular views of the Pacific, perfect for sipping morning coffee or watching the sunset.The ambiance is defined by the spirit of Aloha—warmth, peace, and genuine hospitality. The air is perpetually sweet with the scent of plumeria and salt, encouraging an instant state of relaxation.", category: "Honeymoon Packages" },
  { id: 20, name: "Thailand Island Honeymoon", img: ThailandIslandHoneymoonImg, days: "4 Days", place: "Thailand", price: "₹1,10,000", desc: "A Thailand Island Honeymoon is a glorious escape into a world of exotic beauty, warm hospitality, and pure tropical bliss. It’s a journey across the Andaman Sea and Gulf of Thailand, offering an unforgettable blend of adventure and relaxation.The scene is breathtaking: towering limestone karsts rising dramatically from sapphire waters, miles of powdery white sand beaches, and waters so clear they reveal vibrant coral reefs just below the surface.Accommodation varies from ultra-luxurious pool villas in Phuket or Koh Samui to chic, secluded bungalows on quieter islands like Koh Lanta or Koh Yao, all offering spectacular ocean vistas and privacy.The ambiance is defined by the famous Thai spirit of sanuk (fun) and the inherent tranquility of island life. The air is fragrant with jasmine, salt, and the delicious aroma of street food spices.Days are filled with intimate exploration and shared discovery. Couples can rent a private longtail boat to discover hidden lagoons and untouched coves, or go snorkeling and diving in the marine-rich waters of the Similan Islands.", category: "Honeymoon Packages" },
  { id: 21, name: "Swiss Romantic Honeymoon", img: SwissRomanticHoneymoonImg, days: "5 Days", place: "Switzerland", price: "₹2,30,000", desc: "A Swiss Romantic Honeymoon is an unparalleled escape into a landscape of majestic mountains, pristine lakes, and storybook villages. It is an elegant journey defined by its breathtaking scenery and high standard of intimate luxury.The setting is characterized by the stunning contrast between the dramatic, snow-capped peaks—including iconic landmarks like the Matterhorn and Jungfraujoch—and the serene, deep turquoise or emerald-green valleys below.Accommodation is often a traditional, luxurious chalet or a grand Belle Époque hotel in renowned destinations like Interlaken, Lucerne, or St. Moritz. These spaces offer cozy refinement, often featuring private fireplaces and balconies with panoramic mountain views.The essence of the honeymoon is shared adventure and cozy warmth. Days are filled with unforgettable scenic rail journeys, such as the Glacier Express or the GoldenPass Line, where you witness the spectacular Swiss landscape unfold from your panoramic window.", category: "Honeymoon Packages" },
  { id: 22, name: "Bali Luxury Honeymoon", img: BaliLuxuryHoneymoonImg, days: "4 Days", place: "Bali", price: "₹95,000", desc: "A Bali Luxury Honeymoon is an exquisite journey into tropical indulgence, offering couples a serene sanctuary where world-class luxury meets the profound spiritual beauty of the Indonesian islands.The setting is one of unparalleled natural grace: from the terraced green rice fields of Ubud to the dramatic clifftop views of Uluwatu and the pristine sands of Seminyak. Every view is a masterpiece of vibrant colour and tranquility.Accommodation is uncompromisingly luxurious, often found in a private pool villa nestled in the jungle or dramatically perched on a cliff edge. These villas feature personalized butler service, outdoor bathrooms, and complete, intimate seclusion.The experience is centered around wellness and profound connection. Days are spent indulging in couples’ spa rituals, perhaps featuring traditional Balinese healing therapies in an open-air pavilion surrounded by nature.", category: "Honeymoon Packages" },
  { id: 23, name: "Italy Honeymoon Package", img: ItalyHoneymoonImg, days: "5 Days", place: "Italy", price: "₹2,20,000", desc: "An Italy Honeymoon Package is an immersion into timeless romance and captivating beauty, a journey that weaves together the world's finest art, richest history, and most delectable cuisine.The trip is often a multi-region adventure, designed to showcase the diverse landscapes: from the classical ruins and vibrant energy of Rome to the Renaissance art of Florence and the unique coastal beauty of the south.The romance of Italy is immediately tangible. In Venice, couples experience the quiet intimacy of a gondola ride through the narrow canals, the sound of water and song echoing off ancient stone palaces.In the Tuscan countryside, the escape becomes rustic and serene. Days are spent driving through rolling hills capped with cypress trees, visiting medieval hilltop towns, and indulging in private wine tastings at historic vineyards.", category: "Honeymoon Packages" },
  { id: 24, name: "Japan Honeymoon Experience", img: JapanHoneymoonImg, days: "5 Days", place: "Japan", price: "₹2,00,000", desc: "A Japan Honeymoon is a sophisticated and deeply rewarding journey, blending serene, ancient traditions with the thrilling efficiency of the future. It offers couples a cultural immersion unlike anywhere else.The escape begins with the dazzling, neon-lit energy of Tokyo, where couples can explore cutting-edge architecture, experience world-class dining, and enjoy breathtaking city views from towering skyscrapers.The journey quickly shifts to the profound calm of Kyoto, the cultural heart of Japan. Here, the romance is found strolling hand-in-hand through historic districts like Gion, discovering centuries-old temples and serene Zen gardens.The landscape is breathtakingly beautiful, especially during the cherry blossom (sakura) or autumn foliage seasons, adding an ethereal, romantic glow to every sightseeing moment.", category: "Honeymoon Packages" },

  /* Solo Packages */
  { id: 25, name: "Goa Solo Adventure", img: GoaSoloAdventureImg, days: "3 Days", place: "Goa", price: "₹18,000", desc: "A Goa Solo Adventure is an incredibly liberating and soulful journey into India's beloved coastal haven. It’s an escape dedicated to self-discovery, vibrant culture, and soaking up the state's famously relaxed susegad (easygoing) spirit.The setting is a spectacular contrast between the bustling energy of North Goa's beaches and the serene, quiet charm of the South. You have the freedom to choose your backdrop: from the party vibe of Baga to the tranquil shores of Palolem.Accommodation is flexible and charming, ranging from bohemian beach shacks and cozy homestays to boutique hostels, making it easy to meet fellow travelers or find complete solitude when desired.The days are entirely your own to design. An adventure might start with a solo scooter ride through the lush, green hinterlands, discovering hidden waterfalls or the quiet, colonial-era backroads of Old Goa.", category: "Solo Traveling Packages" },
  { id: 26, name: "Rajasthan Solo Heritage Tour", img: RajasthanSoloHeritageImg, days: "4 Days", place: "Rajasthan", price: "₹25,000", desc: "A Rajasthan Solo Heritage Tour is a deeply enriching and independent adventure into the Land of Kings, a journey dedicated to exploring the magnificent forts, opulent palaces, and rich cultural tapestry of the region.The experience is defined by the stunning visual landscape: from the pink sandstone of Jaipur to the golden citadel of Jaisalmer and the indigo houses of Jodhpur, each city offers a unique, historical hue.Accommodation often features staying in characterful, renovated heritage hotels or havelis (traditional mansions), which offer an authentic and safe atmosphere, blending historical charm with modern comfort.The freedom of solo travel allows for deep, personal immersion into the culture. Days are spent independently navigating the maze-like streets of the old cities, discovering hidden temples, and browsing vibrant spice and textile bazaars.", category: "Solo Traveling Packages" },
  { id: 27, name: "Kerala Solo Explorer", img: KeralaSoloExplorerImg, days: "3 Days", place: "Kerala", price: "₹20,000", desc: "A Kerala Solo Explorer trip is an immersive and meditative adventure through one of India's most verdant and tranquil states. It’s an escape dedicated to quiet contemplation, tropical beauty, and rich cultural discovery.The journey often begins in the historical port of Fort Kochi, where the atmosphere is laid-back and art-focused. Here, you can spend days wandering the colonial streets, examining the iconic Chinese Fishing Nets, and discovering local art galleries and quirky cafes.The landscape is defined by its lush, tropical greenery: dense coconut groves, expansive tea plantations, and the vast, tranquil network of the backwaters. Kerala's unique geography lends itself perfectly to solo reflection.A key part of the adventure is a solitary journey through the Backwaters of Alleppey or Kumarakom. You might hire a small canoe or take a local ferry, gliding past paddy fields and villages, experiencing a rare sense of peace.", category: "Solo Traveling Packages" },
  { id: 28, name: "Thailand Solo Backpacker Tour", img: ThailandSoloBackpackerImg, days: "4 Days", place: "Thailand", price: "₹35,000", desc: "A Thailand Solo Backpacker Tour is an accessible and electrifying rite of passage, offering independent travelers an unparalleled blend of vibrant culture, stunning natural beauty, and a friendly, well-established travel infrastructure.The journey often begins in the bustling, exciting streets of Bangkok, where solo exploration is easy—from navigating the intricate canal systems by boat to exploring the magnificent golden temples like Wat Arun.The adventure moves north to the cultural hub of Chiang Mai, known for its historical Old City walls and as a gateway to ethical elephant sanctuaries and challenging jungle treks, making it easy to meet fellow adventurers.The true appeal is the ease of connection. Hostels are abundant, social, and a fantastic place to form impromptu travel groups for everything from market visits to scooter rentals, sharing costs and experiences.The next phase often involves island hopping down south. Destinations like Koh Phangan, Koh Lanta, and Koh Tao offer stunning beaches, world-class diving certification (which is highly social), and endless opportunities for seaside relaxation.The transport itself is part of the experience: navigating the country via sleeper trains and overnight buses, which are efficient, cost-effective, and surprisingly comfortable, adding a layer of authenticity to the travel.", category: "Solo Traveling Packages" },
  { id: 29, name: "Europe Solo Explorer", img: EuropeSoloExplorerImg, days: "6 Days", place: "Europe", price: "₹1,80,000", desc: "A Europe Solo Explorer journey is a magnificent, self-directed odyssey across a continent rich in layered history, stunning artistry, and diverse cultural identities, making it an ideal destination for independent travelers.The appeal lies in the ease of movement. Europe's extensive, highly efficient network of trains—from the high-speed rail lines to scenic regional routes—makes shifting from the ancient ruins of Rome to the modern flair of Berlin incredibly seamless.The experience is centered on unlimited cultural immersion. Solo travelers have the freedom to spend an entire afternoon lost in the halls of the Louvre, quietly people-watch in a Parisian café, or stumble upon a hidden square in Florence.Accommodation is varied and social, often involving staying in well-located, high-quality hostels or boutique guesthouses, which provide excellent opportunities to meet fellow travelers and share sightseeing tips.", category: "Solo Traveling Packages" },
  { id: 30, name: "Himachal Solo Trekking", img: HimachalSoloTrekkingImg, days: "4 Days", place: "Himachal", price: "₹22,000", desc: "A Himachal Solo Trekking journey is a deeply personal and invigorating test of endurance and self-reliance, set against the breathtaking, silent grandeur of the Himalayan ranges.The experience is centered on the stark, dramatic contrasts of the region: from walking through dense cedar and rhododendron forests to emerging into vast, sunny alpine meadows and finally reaching high-altitude snow lines.Solo trekkers are drawn to famous routes like Triund, Bhrigu Lake, or Kheerganga, known for their well-marked trails and a mix of other independent travelers, offering safety while preserving the feeling of solitude.The primary goal is the uninterrupted connection with nature. Days are spent walking at your own pace, with only the sound of your own steps, the wind through the pines, and the distant rush of a glacial stream.", category: "Solo Traveling Packages" },

  /* Family Packages */
  { id: 31, name: "Goa Family Fun Trip", img: GoaFamilyFunTripImg, days: "3 Days", place: "Goa", price: "₹30,000", desc: "A Goa Family Fun Trip is a perfect blend of beachy relaxation, cultural exploration, and exciting activities, making it an easy and rewarding destination for multi-generational travel.The atmosphere is one of laid-back susegad (easygoingness), creating an instant mood of relaxation for parents, while the golden sands and warm waters promise endless entertainment for children.The setting is diverse, offering options for every family's pace: from the family-friendly resorts and calm waters of South Goa's Benaulim and Varca beaches to the livelier yet accessible areas of North Goa like Candolim.Accommodation is comfortable and accommodating, often featuring spacious resort rooms or serviced villas with dedicated kids' clubs, swimming pools, and extensive buffet spreads to cater to picky eaters.Days are filled with shared activities. A highlight is spending time on the beach, building sandcastles, or engaging in safe water sports like banana boat rides and parasailing suitable for older children.", category: "Family Packages" },
  { id: 32, name: "Rajasthan Family Heritage Tour", img: RajasthanFamilyHeritageImg, days: "4 Days", place: "Rajasthan", price: "₹40,000", desc: "A Rajasthan Family Heritage Tour is a majestic and educational adventure, transforming the rich history of India into a thrilling, tangible experience for the entire family, amidst palaces and desert forts.The landscape is dominated by awe-inspiring architecture, where every city feels like an open-air museum. From the Pink City of Jaipur to the Blue City of Jodhpur, the vibrant colors and dramatic backdrops captivate children and adults alike.Accommodation often features staying in atmospheric heritage hotels or family-friendly resorts that offer spacious rooms, large pools, and grounds where kids can safely explore, blending royal charm with modern comfort.The journey is carefully curated to be interactive and engaging. The primary activity involves exploring the monumental forts and palaces, which become fantastic playgrounds for imagination, transforming history into exciting tales of kings and queens.", category: "Family Packages" },
  { id: 33, name: "Kerala Family Adventure", img: KeralaFamilyAdventureImg, days: "4 Days", place: "Kerala", price: "₹38,000", desc: "A Kerala Family Adventure is a refreshing and unique immersion into nature's tranquility, offering a seamless mix of lush green landscapes, cultural heritage, and engaging activities for every member of the family.The trip is defined by its diverse geography: from the serene, palm-fringed backwaters of Alleppey to the cool, spice-scented mountains of Munnar, and the historic streets of Fort Kochi.Accommodation provides authentic charm and comfort. Staying in a traditional houseboat (Kettuvallam) for a night on the backwaters is a highlight, offering a unique, floating hotel experience the children will adore.The primary family activity is the backwater exploration. You spend hours gliding slowly through the canals, witnessing local village life, paddy fields, and spotting water birds, providing a peaceful change of pace.The adventure continues in the cooler air of the Western Ghats. In Munnar or Thekkady, families can visit vast tea and spice plantations, where guided tours are both educational and sensory, allowing children to touch and smell exotic spices.", category: "Family Packages" },
  { id: 34, name: "Himachal Family Trip", img: HimachalFamilyTripImg, days: "4 Days", place: "Himachal", price: "₹42,000", desc: "A Himachal Family Trip is a wonderful blend of majestic mountain scenery, exhilarating outdoor activities, and serene moments, making it an ideal destination for an enriching family vacation.The setting is spectacular: towering, snow-capped Himalayan peaks, deep, forested valleys, and gushing rivers create a dramatic and beautiful playground that instantly captivates children and adults.The itinerary often includes charming destinations like Shimla, Manali, and Dharamshala, each offering unique experiences, from historical colonial architecture to vibrant Tibetan Buddhist culture.Accommodation ranges from comfortable, resort-style hotels with plenty of amenities to cozy, traditional family-run guesthouses, ensuring a warm and authentic stay with stunning views.", category: "Family Packages" },

  /* Student Packages */
  { id: 35, name: "Educational Trip to Rajasthan", img: RajasthanEducationalTripImg, days: "3 Days", place: "Rajasthan", price: "₹18,000", desc: "An Educational Trip to Rajasthan is a profound journey into the heart of India's past, transforming the study of history, architecture, and sociology into a vibrant, tangible, and unforgettable learning experience.The state serves as a colossal, open-air classroom, defined by its monumental forts and opulent palaces, which offer direct insight into the political and military strategies of the Rajput era.The focus is on architectural analysis and historical context. Students explore masterpieces like the Amber Fort (Jaipur), the Mehrangarh Fort (Jodhpur), and the Golden Fort (Jaisalmer), studying their defensive structures, water management systems, and intricate details.The culture is a central pillar of the learning. Students engage with the traditional arts and crafts, visiting artisan villages to understand block printing, miniature painting, and gem cutting, witnessing the continuity of generational skills.A key educational component is understanding desert ecology and life. A trip to the Thar Desert area highlights sustainable living, water scarcity, and the unique cultural adaptations of the people, such as music and folk tales.", category: "Student Packages" },
  { id: 36, name: "Goa Beach Student Trip", img: GoaBeachStudentTripImg, days: "3 Days", place: "Goa", price: "₹15,000", desc: "A Goa Beach Student Trip is an unforgettable blend of high energy, independent exploration, and laid-back coastal life, providing a perfect, budget-conscious backdrop for student travelers.The atmosphere is famously easygoing and welcoming (susegad), offering students a safe yet vibrant environment to socialize and unwind after periods of intense study or exams.The setting is diverse, offering choices from the buzzing nightlife and flea markets of North Goa (Anjuna, Baga) to the calmer, more secluded stretches of sand in the South (Palolem, Agonda).Accommodation is geared towards group and budget travel, featuring numerous social hostels, affordable guesthouses, and comfortable, shared beach shacks, making it easy to meet fellow travelers.The days are filled with spontaneous, fun activities. A key element is renting scooters to explore the coast and countryside independently, discovering hidden beaches and small villages at their own pace.The beaches are the central hub for relaxation, sunbathing, casual volleyball games, and enjoying the cheap, delicious food from the numerous shacks that line the shore.", category: "Student Packages" },
  { id: 37, name: "Himachal Adventure Trip", img: HimachalAdventureTripImg, days: "4 Days", place: "Himachal", price: "₹22,000", desc: "A Himachal Adventure Trip is a magnificent and exhilarating journey into India's adventure capital, offering diverse, high-adrenaline activities set against the backdrop of the spectacular, rugged Western Himalayas.The setting is characterized by dramatic, varied terrain: towering peaks, deep river valleys carved by the Beas and Ravi rivers, dense cedar forests, and vast alpine meadows.The trip is often centered around key hubs like Manali, Kullu, and Dharamshala, each providing specialized access to different types of thrills, making it perfect for adrenaline seekers.A major focus is trekking and mountaineering. Challenging routes like the Beas Kund Trek or the Hampta Pass offer multi-day journeys, testing endurance and rewarding participants with breathtaking panoramic views of the high peaks.The rivers provide the next thrill: the waters of the Beas River are renowned for offering some of the best white-water rafting in India, navigating challenging rapids amidst stunning valley scenery.", category: "Student Packages" },
  { id: 38, name: "Kerala Educational & Adventure Tour", img: KeralaEducationalTourImg, days: "3 Days", place: "Kerala", price: "₹20,000", desc: "A Kerala Educational & Adventure Tour is a vibrant, multi-faceted journey that perfectly integrates hands-on learning with gentle, invigorating adventure, set against the state's lush tropical landscapes.The educational aspect begins in Fort Kochi, a living history book. Students analyze the colonial legacy, studying the unique architecture, the ancient Chinese Fishing Nets, and the blend of Portuguese, Dutch, and British influences in the streets and spice markets.Cultural learning is immersive. The itinerary includes visits to local villages to witness traditional crafts, attend a mesmerizing Kathakali dance performance to understand Kerala’s narrative arts, and learn about the regional use of Ayurveda and spices.The journey continues into the Backwaters, offering a unique lesson in geography and sustainable living. Traveling by houseboat provides direct insight into the unique ecosystem, local farming, and life dependent on the water canals.", category: "Student Packages" },
  { id: 39, name: "Kolkata & Delhi History Tour", img: KolkataDelhiHistoryTourImg, days: "4 Days", place: "Kolkata & Delhi", price: "₹25,000", desc: "A Kolkata & Delhi History Tour is a profound and captivating journey through centuries of imperial power, political change, and cultural evolution, comparing two of India's most influential cities.The tour begins in Kolkata (Calcutta), the former capital of the British Raj. The focus here is on the colonial legacy, exploring grand Victorian architecture, vast public gardens, and institutions like the Victoria Memorial and the Indian Museum.The educational aspect involves analyzing Kolkata's role as the intellectual and political hub of colonial India, studying the impact of the Bengal Renaissance and the city's unique, fading elegance and vibrant street culture.The journey then moves to Delhi, which offers a magnificent contrast, exploring multiple layers of imperial history—from the Mughal Empire to the current capital of independent India.Old Delhi is a lesson in Mughal glory and urban chaos. Exploration includes the colossal Red Fort (Lal Qila), the majestic Jama Masjid, and the winding lanes of Chandni Chowk, detailing the architecture and social structure of the 17th century.", category: "Student Packages" },
];

/* --------------------- CATEGORIES --------------------- */
export const categories = [
  "Wedding Packages",
  "Couples Packages",
  "Honeymoon Packages",
  "Solo Traveling Packages",
  "Family Packages",
  "Student Packages",
];


export default packagesData;